# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/19165/Downloads/zedboard_LEDs-master/zedboard_LEDs-master/zed_LEDs.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
# IP: The module: 'design_1_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/19165/Downloads/zedboard_LEDs-master/zedboard_LEDs-master/zed_LEDs.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/19165/Downloads/zedboard_LEDs-master/zedboard_LEDs-master/zed_LEDs.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
# IP: The module: 'design_1_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/19165/Downloads/zedboard_LEDs-master/zedboard_LEDs-master/zed_LEDs.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
